### ISSUE TITLE
Please clarify "Diagonally right and up"

### ISSUE THREAD

**Issue by firecentaur** [riipen/gold-mine#27]
Hi there, in the README, the documentation mentions that the miner can move "diagonally right and up".  This is a bit confusing, so I wonder if you can clarify.  Does it mean that in one turn, the miner can move to #7 (column 2, row 1)?
or do you mean column 2, row 2 (which would be a value of 8)

If it is col 2 row 2, I would recommend you remove the wording "and up" and rather just state "can move "diagonally right upwards"
and "diagonally right downwards" - the word "and up" feels like it could be two moves.

Just a suggestion - let me know if you agree. Thanks!

**Comment by jordanell** [comment]
Thanks for the suggestion @firecentaur ! I agree with your suggestion and will make the needed documentation updates.

**Comment by jordanell** [comment]
Fixed in https://github.com/riipen/gold-mine/commit/acd227443106e5c3008da4e070cb8e198008c8e0.
